#!/usr/bin/env bash
# Regenerate shared/abis.ts from the Foundry build output.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT/contracts" && forge build >/dev/null
OUT="$ROOT/shared/abis.ts"
{
  echo "// Generated by scripts/export-abi.sh — do not edit."
  for pair in registry:ComplianceRegistry guard:ComplianceGuard token:MockUSDG; do
    name=${pair%%:*}; contract=${pair##*:}
    echo "export const ${name}Abi = $(jq '.abi' "out/$contract.sol/$contract.json") as const;"
  done
} > "$OUT"
echo "wrote $OUT" >&2
